# Generated by Django 6.0 on 2026-02-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
